---
title: "Hw 2"
author: "Connor Eastman"
date: "2024-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(ggplot2)

soccer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-04/soccer21-22.csv')
```

# Premier League Match Data: 2021-2022
Data Retrieved from [TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-04-04/readme.md)


```{r}
team_stats_Home = soccer %>%
  group_by(HomeTeam) %>%
  summarise(
    home_wins = sum(FTR == "H"),
    home_losses = sum(FTR == "A"),
    home_draws = sum(FTR == "D")
  ) %>%
  rename(team_ID = HomeTeam)

team_stats_Away = soccer %>%
  group_by(AwayTeam) %>%
  summarise(
    away_wins = sum(FTR == "A"),
    away_losses = sum(FTR == "H"),
    away_draws = sum(FTR == "D")
  ) %>%
  rename(team_ID = AwayTeam)

complete_team_stats <- full_join(team_stats_Home, team_stats_Away, by = "team_ID")

complete_team_stats = complete_team_stats %>%
  mutate(total_wins = home_wins+away_wins, 
         total_losses = home_losses+away_losses, 
         total_draws = home_draws+away_draws)

# head(complete_team_stats)
```

```{r}
plot_stats = function(team_name, loc) {
  wins = paste(loc, "_wins", sep="") 
  losses = paste(loc, "_losses", sep="") 
  draws = paste(loc, "_draws", sep="") 
  
  team_data <- complete_team_stats %>%
    filter(team_ID == team_name) %>%
    select(team_ID, Wins = wins, Losses = losses, Draws = draws) %>%
    gather(key = "Statistic", value = "Count", -team_ID)
  
  ggplot(team_data, aes(x = Statistic, y = Count, fill = Statistic)) +
    geom_bar(stat = "identity", alpha=1, show.legend = FALSE) +
    theme_minimal() +
    labs(title = paste(toupper(loc), "Wins, Losses, and Draws for", team_name),
         x = "Outcome",
         y = "Count") +
    scale_x_discrete(labels = c(wins = "Wins", losses = "Losses", draws = "Draws"))
}

```



```{r}
ui = fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("team", "Team", unique(soccer$HomeTeam)),
      radioButtons("location", "Location", c("Total" = "total",
                                             "Home" = "home",
                                             "Away" = "away"))
    ),
    mainPanel(
      plotOutput("team_stats")
    )
  )
)

server = function(input, output) {
  output$team_stats = renderPlot(
    plot_stats(input$team,
               input$location)
    
  )
}

shinyApp(ui, server)
```

